spring:
  data:
    mongodb:
      uri: mongodb+srv://pramod:admin@db01.ege9xlf.mongodb.net/user?retryWrites=true&w=majority
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
